import React from 'react';
import PropTypes from 'prop-types';
import ReactMarkdown from 'react-markdown';

const MARKDOWN_INLINE_COMPONENTS = {
  p: (props) => <span {...props} />,
};

const formatGeneratedAtLegacy = (value) => {
  if (!value || typeof value !== 'string') return '';
  return value.replace('T', ' ').replace('Z', '');
};

const FeedBasicInfo = ({ header }) => {
  if (!header) return null;

  return (
    <>
      <h3>Basic Info</h3>
      <ul className="feed-basic-info">
        {header.model && header.generatedAt ? (
          <li>
            This report was automatically generated by {header.model} at{' '}
            {formatGeneratedAtLegacy(header.generatedAt)}.
          </li>
        ) : null}
        {Array.isArray(header.notes) ? header.notes.map((note) => (
          <li key={note}>
            <ReactMarkdown components={MARKDOWN_INLINE_COMPONENTS}>
              {note}
            </ReactMarkdown>
          </li>
        )) : null}
      </ul>
    </>
  );
};

FeedBasicInfo.propTypes = {
  header: PropTypes.shape({
    model: PropTypes.string,
    generatedAt: PropTypes.string,
    notes: PropTypes.arrayOf(PropTypes.string),
  }),
};

FeedBasicInfo.defaultProps = {
  header: null,
};

export default FeedBasicInfo;
